// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: zmk/battery_history/battery_history.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "zmk.battery_history";

/** Battery level reading at a specific time */
export interface BatteryReading {
  /** Unix timestamp in milliseconds */
  timestampMs: number;
  /** Battery level (0-100) */
  level: number;
  /** Whether battery is currently charging */
  isCharging: boolean;
}

/** Battery information for a keyboard half */
export interface BatteryInfo {
  /** e.g., "Left", "Right", "Central" */
  deviceName: string;
  /** Current battery level (0-100) */
  currentLevel: number;
  /** Whether currently charging */
  isCharging: boolean;
  /** Unix timestamp of last update */
  lastUpdatedMs: number;
  /** Historical readings */
  history: BatteryReading[];
}

/** Get current battery status */
export interface GetBatteryStatusRequest {
}

export interface GetBatteryStatusResponse {
  /** One or more batteries (for split keyboards) */
  batteries: BatteryInfo[];
}

/** Get battery history */
export interface GetBatteryHistoryRequest {
  /** Start of time range (optional) */
  startTimeMs: number;
  /** End of time range (optional) */
  endTimeMs: number;
  /** Maximum number of entries to return (optional) */
  maxEntries: number;
}

export interface GetBatteryHistoryResponse {
  /** Battery history for each device */
  batteries: BatteryInfo[];
}

/** Main request/response wrapper */
export interface Request {
  getBatteryStatus?: GetBatteryStatusRequest | undefined;
  getBatteryHistory?: GetBatteryHistoryRequest | undefined;
}

export interface ErrorResponse {
  message: string;
}

export interface Response {
  error?: ErrorResponse | undefined;
  getBatteryStatus?: GetBatteryStatusResponse | undefined;
  getBatteryHistory?: GetBatteryHistoryResponse | undefined;
}

function createBaseBatteryReading(): BatteryReading {
  return { timestampMs: 0, level: 0, isCharging: false };
}

export const BatteryReading: MessageFns<BatteryReading> = {
  encode(message: BatteryReading, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.timestampMs !== 0) {
      writer.uint32(8).uint64(message.timestampMs);
    }
    if (message.level !== 0) {
      writer.uint32(16).uint32(message.level);
    }
    if (message.isCharging !== false) {
      writer.uint32(24).bool(message.isCharging);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BatteryReading {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBatteryReading();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.timestampMs = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.level = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.isCharging = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<BatteryReading>): BatteryReading {
    return BatteryReading.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<BatteryReading>): BatteryReading {
    const message = createBaseBatteryReading();
    message.timestampMs = object.timestampMs ?? 0;
    message.level = object.level ?? 0;
    message.isCharging = object.isCharging ?? false;
    return message;
  },
};

function createBaseBatteryInfo(): BatteryInfo {
  return { deviceName: "", currentLevel: 0, isCharging: false, lastUpdatedMs: 0, history: [] };
}

export const BatteryInfo: MessageFns<BatteryInfo> = {
  encode(message: BatteryInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.deviceName !== "") {
      writer.uint32(10).string(message.deviceName);
    }
    if (message.currentLevel !== 0) {
      writer.uint32(16).uint32(message.currentLevel);
    }
    if (message.isCharging !== false) {
      writer.uint32(24).bool(message.isCharging);
    }
    if (message.lastUpdatedMs !== 0) {
      writer.uint32(32).uint64(message.lastUpdatedMs);
    }
    for (const v of message.history) {
      BatteryReading.encode(v!, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BatteryInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBatteryInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.deviceName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.currentLevel = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.isCharging = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.lastUpdatedMs = longToNumber(reader.uint64());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.history.push(BatteryReading.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<BatteryInfo>): BatteryInfo {
    return BatteryInfo.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<BatteryInfo>): BatteryInfo {
    const message = createBaseBatteryInfo();
    message.deviceName = object.deviceName ?? "";
    message.currentLevel = object.currentLevel ?? 0;
    message.isCharging = object.isCharging ?? false;
    message.lastUpdatedMs = object.lastUpdatedMs ?? 0;
    message.history = object.history?.map((e) => BatteryReading.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetBatteryStatusRequest(): GetBatteryStatusRequest {
  return {};
}

export const GetBatteryStatusRequest: MessageFns<GetBatteryStatusRequest> = {
  encode(_: GetBatteryStatusRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetBatteryStatusRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBatteryStatusRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetBatteryStatusRequest>): GetBatteryStatusRequest {
    return GetBatteryStatusRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<GetBatteryStatusRequest>): GetBatteryStatusRequest {
    const message = createBaseGetBatteryStatusRequest();
    return message;
  },
};

function createBaseGetBatteryStatusResponse(): GetBatteryStatusResponse {
  return { batteries: [] };
}

export const GetBatteryStatusResponse: MessageFns<GetBatteryStatusResponse> = {
  encode(message: GetBatteryStatusResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.batteries) {
      BatteryInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetBatteryStatusResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBatteryStatusResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.batteries.push(BatteryInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetBatteryStatusResponse>): GetBatteryStatusResponse {
    return GetBatteryStatusResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetBatteryStatusResponse>): GetBatteryStatusResponse {
    const message = createBaseGetBatteryStatusResponse();
    message.batteries = object.batteries?.map((e) => BatteryInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetBatteryHistoryRequest(): GetBatteryHistoryRequest {
  return { startTimeMs: 0, endTimeMs: 0, maxEntries: 0 };
}

export const GetBatteryHistoryRequest: MessageFns<GetBatteryHistoryRequest> = {
  encode(message: GetBatteryHistoryRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.startTimeMs !== 0) {
      writer.uint32(8).uint64(message.startTimeMs);
    }
    if (message.endTimeMs !== 0) {
      writer.uint32(16).uint64(message.endTimeMs);
    }
    if (message.maxEntries !== 0) {
      writer.uint32(24).uint32(message.maxEntries);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetBatteryHistoryRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBatteryHistoryRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.startTimeMs = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.endTimeMs = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.maxEntries = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetBatteryHistoryRequest>): GetBatteryHistoryRequest {
    return GetBatteryHistoryRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetBatteryHistoryRequest>): GetBatteryHistoryRequest {
    const message = createBaseGetBatteryHistoryRequest();
    message.startTimeMs = object.startTimeMs ?? 0;
    message.endTimeMs = object.endTimeMs ?? 0;
    message.maxEntries = object.maxEntries ?? 0;
    return message;
  },
};

function createBaseGetBatteryHistoryResponse(): GetBatteryHistoryResponse {
  return { batteries: [] };
}

export const GetBatteryHistoryResponse: MessageFns<GetBatteryHistoryResponse> = {
  encode(message: GetBatteryHistoryResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.batteries) {
      BatteryInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetBatteryHistoryResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBatteryHistoryResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.batteries.push(BatteryInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetBatteryHistoryResponse>): GetBatteryHistoryResponse {
    return GetBatteryHistoryResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetBatteryHistoryResponse>): GetBatteryHistoryResponse {
    const message = createBaseGetBatteryHistoryResponse();
    message.batteries = object.batteries?.map((e) => BatteryInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseRequest(): Request {
  return { getBatteryStatus: undefined, getBatteryHistory: undefined };
}

export const Request: MessageFns<Request> = {
  encode(message: Request, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.getBatteryStatus !== undefined) {
      GetBatteryStatusRequest.encode(message.getBatteryStatus, writer.uint32(10).fork()).join();
    }
    if (message.getBatteryHistory !== undefined) {
      GetBatteryHistoryRequest.encode(message.getBatteryHistory, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.getBatteryStatus = GetBatteryStatusRequest.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.getBatteryHistory = GetBatteryHistoryRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Request>): Request {
    return Request.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Request>): Request {
    const message = createBaseRequest();
    message.getBatteryStatus = (object.getBatteryStatus !== undefined && object.getBatteryStatus !== null)
      ? GetBatteryStatusRequest.fromPartial(object.getBatteryStatus)
      : undefined;
    message.getBatteryHistory = (object.getBatteryHistory !== undefined && object.getBatteryHistory !== null)
      ? GetBatteryHistoryRequest.fromPartial(object.getBatteryHistory)
      : undefined;
    return message;
  },
};

function createBaseErrorResponse(): ErrorResponse {
  return { message: "" };
}

export const ErrorResponse: MessageFns<ErrorResponse> = {
  encode(message: ErrorResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ErrorResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseErrorResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ErrorResponse>): ErrorResponse {
    return ErrorResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ErrorResponse>): ErrorResponse {
    const message = createBaseErrorResponse();
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseResponse(): Response {
  return { error: undefined, getBatteryStatus: undefined, getBatteryHistory: undefined };
}

export const Response: MessageFns<Response> = {
  encode(message: Response, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.error !== undefined) {
      ErrorResponse.encode(message.error, writer.uint32(10).fork()).join();
    }
    if (message.getBatteryStatus !== undefined) {
      GetBatteryStatusResponse.encode(message.getBatteryStatus, writer.uint32(18).fork()).join();
    }
    if (message.getBatteryHistory !== undefined) {
      GetBatteryHistoryResponse.encode(message.getBatteryHistory, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.error = ErrorResponse.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.getBatteryStatus = GetBatteryStatusResponse.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.getBatteryHistory = GetBatteryHistoryResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Response>): Response {
    return Response.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Response>): Response {
    const message = createBaseResponse();
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorResponse.fromPartial(object.error)
      : undefined;
    message.getBatteryStatus = (object.getBatteryStatus !== undefined && object.getBatteryStatus !== null)
      ? GetBatteryStatusResponse.fromPartial(object.getBatteryStatus)
      : undefined;
    message.getBatteryHistory = (object.getBatteryHistory !== undefined && object.getBatteryHistory !== null)
      ? GetBatteryHistoryResponse.fromPartial(object.getBatteryHistory)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
