import { createHash } from "node:crypto";
import fixtures from "./inertiaSimulation.fixtures.json";
import { inertiaExample, simulateInertia } from "../inertiaSimulation";
import type { InertiaSettings } from "../inputInertia";
function settings(config: number[]): InertiaSettings {
  return {
    inertiaEnabled: true,
    inertiaWindowMs: config[0],
    inertiaIntervalMs: config[1],
    inertiaThreshold: config[2],
    inertiaDecayPercent: config[3],
    inertiaNormalMaxOutput: config[4],
    inertiaFastThreshold: config[5],
    inertiaFastOutputPercent: config[6],
  };
}
// Generated by compiling the upstream C add_report/window_total/start/
// handle_physical_event/finish_interval functions from bcf4e727, with host
// stubs for Zephyr timing, an active layer and Kconfig's 64 slices/66 buckets.
// Input before an output tick at identical timestamps; horizon 15000 ms.
it.each(fixtures)("matches upstream C ticks: $name", (fixture) => {
  const m = fixture.config[7],
    d = fixture.config[8];
  let remainder = 0;
  const reports = Array.from({ length: 249 }, (_, i) => {
    const time = (i + 1) * 20;
    const raw = Math.round(
      (fixture.config[9] ?? 40) * (1 - ((time - 3200) / 3200) ** 2),
    );
    const numerator = raw * m + remainder;
    const scaled = Math.trunc(numerator / d);
    remainder = numerator - scaled * d;
    return { time, raw, scaled };
  });
  const ticks = simulateInertia(
    settings(fixture.config),
    reports,
    15000,
    m,
    d,
  ).map((t) => [t.time, t.value, Number(t.fast)]);
  expect(ticks).toHaveLength(fixture.count);
  expect(ticks.reduce((sum, t) => sum + t[1], 0)).toBe(fixture.sum);
  expect(ticks.slice(0, 5)).toEqual(fixture.first);
  expect(ticks.slice(-5)).toEqual(fixture.last);
  expect(createHash("sha256").update(JSON.stringify(ticks)).digest("hex")).toBe(
    fixture.hash,
  );
});
it("uses one five-second truncated parabolic input for both comparisons, and previews enabling Fast when disabled", () => {
  const points = inertiaExample(settings(fixtures[4].config), 1, 1);
  expect(points.find((p) => p.time === 3200)?.input).toBe(40);
  expect(points.find((p) => p.time === 4980)?.input).toBeGreaterThan(0);
  expect(points.find((p) => p.time === 5000)?.input).toBe(0);
  expect(points.filter((p) => p.time > 5000).every((p) => p.input === 0)).toBe(
    true,
  );
  expect(points.some((p) => p.fast > p.normal)).toBe(true);
  const disabled = settings(fixtures[4].config);
  const enabled = { ...disabled, inertiaFastThreshold: 20 };
  expect(points).toEqual(inertiaExample(enabled, 1, 1));
  expect(disabled.inertiaFastThreshold).toBe(0);
  expect(points.some((p) => p.time > 5000 && p.normal > 0)).toBe(true);
});
it("does not emit output below activation threshold or with inertia disabled", () => {
  const s = settings(fixtures[0].config);
  const reports = [{ time: 0, raw: 1, scaled: 1 }];
  expect(simulateInertia(s, reports, 1000)).toEqual([]);
  expect(
    simulateInertia(
      { ...s, inertiaEnabled: false },
      [{ time: 0, raw: 100, scaled: 100 }],
      1000,
    ),
  ).toEqual([]);
});

it("preserves configured Fast thresholds and legitimately equal 100-percent output", () => {
  const s = { ...settings(fixtures[0].config), inertiaFastOutputPercent: 100 };
  expect(inertiaExample(s, 1, 1).every((p) => p.fast === p.normal)).toBe(true);
  expect(
    inertiaExample(
      { ...s, inertiaFastThreshold: 65535, inertiaFastOutputPercent: 200 },
      1,
      10000000,
    ).every((p) => p.fast === p.normal),
  ).toBe(true);
});

it("keeps scroll-scaled input large enough to compare a 300-percent Fast output", () => {
  const s = {
    ...settings(fixtures[0].config),
    inertiaWindowMs: 300,
    inertiaFastThreshold: 15,
    inertiaFastOutputPercent: 300,
  };
  const points = inertiaExample(s, 1, 60);
  expect(Math.max(...points.map((p) => p.input))).toBe(40);
  expect(points.some((p) => p.fast > p.normal)).toBe(true);
  const tail = points.filter((p) => p.time > 5000);
  expect(tail.reduce((sum, p) => sum + p.fast, 0)).toBeGreaterThan(
    tail.reduce((sum, p) => sum + p.normal, 0) * 2,
  );
});

it("supplements physical input and takes over after the latest bucket expires", () => {
  const s = {
    ...settings(fixtures[0].config),
    inertiaWindowMs: 100,
    inertiaThreshold: 1,
    inertiaDecayPercent: 0,
    inertiaFastThreshold: 0,
  };
  const ticks = simulateInertia(
    s,
    [
      { time: 20, raw: 20, scaled: 20 },
      { time: 40, raw: 20, scaled: 20 },
    ],
    80,
  );
  expect(ticks).toEqual([
    { time: 40, value: 0, fast: false },
    { time: 60, value: 8, fast: false },
    { time: 80, value: 8, fast: false },
  ]);
});
