import { createHash } from "node:crypto";
import fixtures from "./inertiaSimulation.fixtures.json";
import { inertiaExample, simulateInertia } from "../inertiaSimulation";
import type { InertiaSettings } from "../inputInertia";
function settings(config: number[]): InertiaSettings {
  return {
    inertiaEnabled: true,
    inertiaWindowMs: config[0],
    inertiaIntervalMs: config[1],
    inertiaThreshold: config[2],
    inertiaDecayPercent: config[3],
    inertiaNormalMaxOutput: config[4],
    inertiaFastThreshold: config[5],
    inertiaFastOutputPercent: config[6],
  };
}
// Generated by compiling the upstream C add_report/window_total/start/
// handle_physical_event/finish_interval functions from 7fa97aca, with host
// stubs for Zephyr timing, an active layer and Kconfig's 64 slices/66 buckets.
// Input before an output tick at identical timestamps; horizon 15000 ms.
it.each(fixtures)("matches upstream C ticks: $name", (fixture) => {
  const m = fixture.config[7],
    d = fixture.config[8];
  let remainder = 0;
  const reports = Array.from({ length: 250 }, (_, i) => {
    const time = (i + 1) * 20;
    const raw = Math.round(40 * (1 - Math.abs((2 * time) / 5000 - 1)));
    const numerator = raw * m + remainder;
    const scaled = Math.trunc(numerator / d);
    remainder = numerator - scaled * d;
    return { time, raw, scaled };
  });
  const ticks = simulateInertia(
    settings(fixture.config),
    reports,
    15000,
    m,
    d,
  ).map((t) => [t.time, t.value, Number(t.fast)]);
  expect(ticks).toHaveLength(fixture.count);
  expect(ticks.reduce((sum, t) => sum + t[1], 0)).toBe(fixture.sum);
  expect(ticks.slice(0, 5)).toEqual(fixture.first);
  expect(ticks.slice(-5)).toEqual(fixture.last);
  expect(createHash("sha256").update(JSON.stringify(ticks)).digest("hex")).toBe(
    fixture.hash,
  );
});
it("uses one five-second mountain input for both comparisons, and honors Fast disabled", () => {
  const points = inertiaExample(settings(fixtures[4].config), 1, 1);
  expect(points.find((p) => p.time === 2500)?.input).toBe(40);
  expect(points.filter((p) => p.time > 5000).every((p) => p.input === 0)).toBe(
    true,
  );
  expect(points.every((p) => p.normal === p.fast)).toBe(true);
  expect(points.some((p) => p.time > 5000 && p.normal > 0)).toBe(true);
});
it("does not emit output below activation threshold or with inertia disabled", () => {
  const s = settings(fixtures[0].config);
  const reports = [{ time: 0, raw: 1, scaled: 1 }];
  expect(simulateInertia(s, reports, 1000)).toEqual([]);
  expect(
    simulateInertia(
      { ...s, inertiaEnabled: false },
      [{ time: 0, raw: 100, scaled: 100 }],
      1000,
    ),
  ).toEqual([]);
});
